"""LanBridge: Open-source protocol compatibility toolkit and SDK for NeiWangTong (Nwt)."""

from __future__ import annotations

__version__ = "0.5.0"

from lanbridge.adapter import NativeNwtAdapter
from lanbridge.client import LanBridgeClient
from lanbridge.discovery import SubnetScanner
from lanbridge.models import (
    ChatMessage,
    Contact,
    FileTask,
    GroupSharedFile,
    QGroup,
    RecallNotice,
    TypingNotice,
    ShakeNotice,
)
from lanbridge.protocol import (
    AesEngine,
    BlowfishEngine,
    ENetCommandType,
    ENetFragmentAssembler,
    ENetProtocolSession,
    Opcode,
    XteaEngine,
    build_discovery_packet,
    build_folder_tran_chunk,
    build_folder_tran_response,
    build_minifile_chunk,
    build_minifile_response,
    build_native_profile,
    build_nwt_discovery_packet,
    build_x_flash_screen_envelope,
    build_x_heartbeat_envelope,
    build_x_qgroup_delete_share_envelope,
    build_x_qgroup_share_file_envelope,
    build_x_ready_envelope,
    build_x_send_image_envelope,
    build_x_send_msg_ack_envelope,
    build_x_send_msg_envelope,
    extract_chat_message,
    extract_msg_id,
    parse_discovery_packet,
    parse_folder_tran_packet,
    parse_minifile_packet,
    ShareOpcode,
)

__all__ = [
    "__version__",
    "NativeNwtAdapter",
    "LanBridgeClient",
    "SubnetScanner",
    "Contact",
    "ChatMessage",
    "FileTask",
    "GroupSharedFile",
    "QGroup",
    "TypingNotice",
    "RecallNotice",
    "ShakeNotice",
    "XteaEngine",
    "BlowfishEngine",
    "AesEngine",
    "ENetProtocolSession",
    "ENetFragmentAssembler",
    "ENetCommandType",
    "Opcode",
    "build_nwt_discovery_packet",
    "parse_discovery_packet",
    "build_native_profile",
    "build_x_send_msg_envelope",
    "build_x_send_image_envelope",
    "build_x_send_msg_ack_envelope",
    "build_x_flash_screen_envelope",
    "build_x_heartbeat_envelope",
    "build_x_ready_envelope",
    "extract_chat_message",
    "extract_msg_id",
    "build_folder_tran_response",
    "build_folder_tran_chunk",
    "parse_folder_tran_packet",
    "build_minifile_response",
    "build_minifile_chunk",
    "parse_minifile_packet",
    "ShareOpcode",
    "build_x_qgroup_share_file_envelope",
    "build_x_qgroup_delete_share_envelope",
]
